# Generated by Django 3.1.1 on 2020-09-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='student_id',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
