# Generated by Django 3.1.1 on 2020-09-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='student_id',
            new_name='id',
        ),
    ]
