# Generated by Django 3.1.1 on 2020-09-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200910_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('semester', models.CharField(choices=[('fifth', 'fifth'), ('sixth', 'sixth'), ('seventh', 'seventh'), ('eighth ', 'eighth')], default='fifth', max_length=7)),
                ('branch', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Computer_Science', 'Computer Science'), ('Electrical ', 'Electrical'), ('Electrical&Electronics ', 'Electrical&Electronics'), ('Information_Technology ', 'Information Technology')], default='Mechanical', max_length=40)),
                ('project_topic', models.CharField(max_length=200)),
                ('project_expert', models.CharField(max_length=150)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
