# Generated by Django 3.1.1 on 2020-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_studentproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='amount',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentproject',
            name='payment_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
