# Generated by Django 3.1.1 on 2020-09-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200917_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='semester',
            field=models.CharField(choices=[('Fifth', 'Fifth'), ('Sixth', 'Sixth'), ('Seventh', 'Seventh'), ('Eighth ', 'Eighth')], default='Fifth', max_length=7),
        ),
    ]
