# Generated by Django 3.1.1 on 2020-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200917_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
