# Generated by Django 3.1.1 on 2020-09-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_studentproject_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='student_id',
            field=models.CharField(max_length=13),
        ),
    ]
