# Generated by Django 3.1.1 on 2020-09-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200917_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
