# Generated by Django 3.1.1 on 2020-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200917_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
