# Generated by Django 3.1.1 on 2020-09-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200917_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentproject',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
