# Generated by Django 3.1.1 on 2020-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
