# Generated by Django 3.1.1 on 2020-09-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200918_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproject',
            name='paid',
        ),
    ]
