# Generated by Django 3.1.1 on 2020-09-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_studentproject_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='amount',
            field=models.IntegerField(default=1000),
        ),
    ]
