# Generated by Django 3.1.1 on 2020-09-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200918_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='phone',
            field=models.CharField(default='4521785415', max_length=12),
        ),
    ]
