# Generated by Django 3.1.1 on 2020-09-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200920_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='project_expert',
            field=models.CharField(choices=[('MEHR', 'Prof Hariram Chandrakar(Mech)-Robotics & Machine Learning'), ('MEPBD', 'Dr. P.B Deshmukh(Mech)-Inernal Combustion Engine'), ('MESV', 'Prof Sankalp Verma(Mech)-Designing'), ('MEAS', 'Prof Abhishek Singh(Mech)-Thermodynamics'), ('MESC', 'Prof Sharad Chandrakar(Mech)-CAD/CAM/CAE'), ('CEAR', 'Prof Aman Rathore(Civil)-Mechanical Properties of Soil'), ('CEVS', 'Prof Vivek Swarnakar(Civil)-Study on Reinforced Compression Members'), ('CEAD', 'Prof Aakash Dubey(Civil)-Advanced Earthquake Resistant Techniques'), ('CEAR', 'Prof Akash Rajput(Civil)-Advance Technology in Surveying'), ('CERT', 'Prof Rahul Tiwari(Civil)-Improvement of bearing capacity of soil'), ('CSERL', 'Prof Renu Lata(CSE)-Database and Information Systems'), ('CSERT', 'Prof Rajesh Tiwari(CSE)-Machine Learning Using Python'), ('CSEAP', 'Prof Ajay Pandey(CSE)-Python for Data Science'), ('CSEAS', 'Prof Aditi Singh(CSE)-Web Development'), ('CSEVR', 'Prof Victor Rossh(CSE)-File System Simulation'), ('ITAW', 'Prof Andrew Wilson(IT)-Android task monitoring'), ('ITGS', 'Prof Gurmeet Singh(IT)-Data Structures'), ('ITPT', 'Prof Pragya Tripathi(IT)-Digital Logic and Design'), ('ITSV', 'Prof Sunita Verma(IT)-Operating Systems'), ('ITKV', 'Prof Kapil Verma(IT)-Cyber Security'), ('EESR', 'Prof Santosh Rai(EE)-Android Based Electrical Appliance Control'), ('EEJKT', 'Prof Jitendra Kumar Tiwari(EE)-Power generation and supply'), ('EENL', 'Prof Neena Lal(EE)-Communications and Media'), ('EERG', 'Prof Rakesh Gupta(EE)-Science and technology research'), ('EEVK', 'Prof Vivek Kumar(EE)-Computer hardware and software design'), ('EEEHR', 'Prof Himanshu Pandey(EEE)-Analog And Digital Electronics'), ('EEEST', 'Prof Shikha Tiwari(EEE)-Signals and System'), ('EEEPC', 'Prof Prateek Chatterjee(EEE)-Network Theory'), ('EEESKS', 'Prof Sarat Kumar Sahu(EEE)-Power Electronics'), ('EEEAK', 'Prof Arun Kumar(EEE)-Analog circuits and power electronics')], default='MEHR', max_length=1000),
        ),
    ]
